// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file service/auth/v1/service.proto (package service.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { IdentityProvider } from "../../../types/v1/identity_provider_pb";
import { file_types_v1_identity_provider } from "../../../types/v1/identity_provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/auth/v1/service.proto.
 */
export const file_service_auth_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1zZXJ2aWNlL2F1dGgvdjEvc2VydmljZS5wcm90bxIPc2VydmljZS5hdXRoLnYxImAKEUdldEF1dGhVUkxSZXF1ZXN0EjUKEWlkZW50aXR5X3Byb3ZpZGVyGAEgASgOMhoudHlwZXMudjEuSWRlbnRpdHlQcm92aWRlchIUCgxjYWxsYmFja191cmwYAiABKAkiJgoSR2V0QXV0aFVSTFJlc3BvbnNlEhAKCGF1dGhfdXJsGAEgASgJIlgKDExvZ2luUmVxdWVzdBI1ChFpZGVudGl0eV9wcm92aWRlchgBIAEoDjIaLnR5cGVzLnYxLklkZW50aXR5UHJvdmlkZXISEQoJYXV0aF9jb2RlGAIgASgJIk4KDUxvZ2luUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJEhIKCnNlc3Npb25faWQYAiABKAkSEwoLaXNfbmV3X3VzZXIYAyABKAgiIwoNTG9nb3V0UmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJIiEKDkxvZ291dFJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgy/QEKC0F1dGhTZXJ2aWNlElcKCkdldEF1dGhVUkwSIi5zZXJ2aWNlLmF1dGgudjEuR2V0QXV0aFVSTFJlcXVlc3QaIy5zZXJ2aWNlLmF1dGgudjEuR2V0QXV0aFVSTFJlc3BvbnNlIgASSAoFTG9naW4SHS5zZXJ2aWNlLmF1dGgudjEuTG9naW5SZXF1ZXN0Gh4uc2VydmljZS5hdXRoLnYxLkxvZ2luUmVzcG9uc2UiABJLCgZMb2dvdXQSHi5zZXJ2aWNlLmF1dGgudjEuTG9nb3V0UmVxdWVzdBofLnNlcnZpY2UuYXV0aC52MS5Mb2dvdXRSZXNwb25zZSIAQjxaOmdpdGh1Yi5jb20vZ2Flc2Vtby90ZWNoLWJsb2ctYXBpL2dvL3NlcnZpY2UvYXV0aC92MTthdXRodjFiBnByb3RvMw", [file_types_v1_identity_provider]);

/**
 * @generated from message service.auth.v1.GetAuthURLRequest
 */
export type GetAuthURLRequest = Message<"service.auth.v1.GetAuthURLRequest"> & {
  /**
   * @generated from field: types.v1.IdentityProvider identity_provider = 1;
   */
  identityProvider: IdentityProvider;

  /**
   * @generated from field: string callback_url = 2;
   */
  callbackUrl: string;
};

/**
 * Describes the message service.auth.v1.GetAuthURLRequest.
 * Use `create(GetAuthURLRequestSchema)` to create a new message.
 */
export const GetAuthURLRequestSchema: GenMessage<GetAuthURLRequest> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 0);

/**
 * @generated from message service.auth.v1.GetAuthURLResponse
 */
export type GetAuthURLResponse = Message<"service.auth.v1.GetAuthURLResponse"> & {
  /**
   * @generated from field: string auth_url = 1;
   */
  authUrl: string;
};

/**
 * Describes the message service.auth.v1.GetAuthURLResponse.
 * Use `create(GetAuthURLResponseSchema)` to create a new message.
 */
export const GetAuthURLResponseSchema: GenMessage<GetAuthURLResponse> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 1);

/**
 * @generated from message service.auth.v1.LoginRequest
 */
export type LoginRequest = Message<"service.auth.v1.LoginRequest"> & {
  /**
   * @generated from field: types.v1.IdentityProvider identity_provider = 1;
   */
  identityProvider: IdentityProvider;

  /**
   * @generated from field: string auth_code = 2;
   */
  authCode: string;
};

/**
 * Describes the message service.auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 2);

/**
 * @generated from message service.auth.v1.LoginResponse
 */
export type LoginResponse = Message<"service.auth.v1.LoginResponse"> & {
  /**
   * jwt
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * uuid
   *
   * @generated from field: string session_id = 2;
   */
  sessionId: string;

  /**
   * @generated from field: bool is_new_user = 3;
   */
  isNewUser: boolean;
};

/**
 * Describes the message service.auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 3);

/**
 * @generated from message service.auth.v1.LogoutRequest
 */
export type LogoutRequest = Message<"service.auth.v1.LogoutRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message service.auth.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 4);

/**
 * @generated from message service.auth.v1.LogoutResponse
 */
export type LogoutResponse = Message<"service.auth.v1.LogoutResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message service.auth.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 5);

/**
 * @generated from service service.auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc service.auth.v1.AuthService.GetAuthURL
   */
  getAuthURL: {
    methodKind: "unary";
    input: typeof GetAuthURLRequestSchema;
    output: typeof GetAuthURLResponseSchema;
  },
  /**
   * @generated from rpc service.auth.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc service.auth.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service_auth_v1_service, 0);

