// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file service/auth/v1/service.proto (package service.auth.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/auth/v1/service.proto.
 */
export const file_service_auth_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1zZXJ2aWNlL2F1dGgvdjEvc2VydmljZS5wcm90bxIPc2VydmljZS5hdXRoLnYxIl8KEUdldEF1dGhVUkxSZXF1ZXN0EjQKDWF1dGhfcHJvdmlkZXIYASABKA4yHS5zZXJ2aWNlLmF1dGgudjEuQXV0aFByb3ZpZGVyEhQKDGNhbGxiYWNrX3VybBgCIAEoCSImChJHZXRBdXRoVVJMUmVzcG9uc2USEAoIYXV0aF91cmwYASABKAkiVwoMTG9naW5SZXF1ZXN0EjQKDWF1dGhfcHJvdmlkZXIYASABKA4yHS5zZXJ2aWNlLmF1dGgudjEuQXV0aFByb3ZpZGVyEhEKCWF1dGhfY29kZRgCIAEoCSJLCg1Mb2dpblJlc3BvbnNlEhQKDGFjY2Vzc190b2tlbhgBIAEoCRIPCgdzZXNzaW9uGAIgASgJEhMKC2lzX25ld191c2VyGAMgASgIIiAKDUxvZ291dFJlcXVlc3QSDwoHc2Vzc2lvbhgBIAEoCSIhCg5Mb2dvdXRSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIKkcKDEF1dGhQcm92aWRlchIdChlBVVRIX1BST1ZJREVSX1VOU1BFQ0lGSUVEEAASGAoUQVVUSF9QUk9WSURFUl9HSVRIVUIQATL9AQoLQXV0aFNlcnZpY2USVwoKR2V0QXV0aFVSTBIiLnNlcnZpY2UuYXV0aC52MS5HZXRBdXRoVVJMUmVxdWVzdBojLnNlcnZpY2UuYXV0aC52MS5HZXRBdXRoVVJMUmVzcG9uc2UiABJICgVMb2dpbhIdLnNlcnZpY2UuYXV0aC52MS5Mb2dpblJlcXVlc3QaHi5zZXJ2aWNlLmF1dGgudjEuTG9naW5SZXNwb25zZSIAEksKBkxvZ291dBIeLnNlcnZpY2UuYXV0aC52MS5Mb2dvdXRSZXF1ZXN0Gh8uc2VydmljZS5hdXRoLnYxLkxvZ291dFJlc3BvbnNlIgBCGFoWc2VydmljZS9hdXRoL3YxO2F1dGh2MWIGcHJvdG8z");

/**
 * @generated from message service.auth.v1.GetAuthURLRequest
 */
export type GetAuthURLRequest = Message<"service.auth.v1.GetAuthURLRequest"> & {
  /**
   * @generated from field: service.auth.v1.AuthProvider auth_provider = 1;
   */
  authProvider: AuthProvider;

  /**
   * @generated from field: string callback_url = 2;
   */
  callbackUrl: string;
};

/**
 * Describes the message service.auth.v1.GetAuthURLRequest.
 * Use `create(GetAuthURLRequestSchema)` to create a new message.
 */
export const GetAuthURLRequestSchema: GenMessage<GetAuthURLRequest> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 0);

/**
 * @generated from message service.auth.v1.GetAuthURLResponse
 */
export type GetAuthURLResponse = Message<"service.auth.v1.GetAuthURLResponse"> & {
  /**
   * @generated from field: string auth_url = 1;
   */
  authUrl: string;
};

/**
 * Describes the message service.auth.v1.GetAuthURLResponse.
 * Use `create(GetAuthURLResponseSchema)` to create a new message.
 */
export const GetAuthURLResponseSchema: GenMessage<GetAuthURLResponse> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 1);

/**
 * @generated from message service.auth.v1.LoginRequest
 */
export type LoginRequest = Message<"service.auth.v1.LoginRequest"> & {
  /**
   * @generated from field: service.auth.v1.AuthProvider auth_provider = 1;
   */
  authProvider: AuthProvider;

  /**
   * @generated from field: string auth_code = 2;
   */
  authCode: string;
};

/**
 * Describes the message service.auth.v1.LoginRequest.
 * Use `create(LoginRequestSchema)` to create a new message.
 */
export const LoginRequestSchema: GenMessage<LoginRequest> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 2);

/**
 * @generated from message service.auth.v1.LoginResponse
 */
export type LoginResponse = Message<"service.auth.v1.LoginResponse"> & {
  /**
   * jwt
   *
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * uuid
   *
   * @generated from field: string session = 2;
   */
  session: string;

  /**
   * @generated from field: bool is_new_user = 3;
   */
  isNewUser: boolean;
};

/**
 * Describes the message service.auth.v1.LoginResponse.
 * Use `create(LoginResponseSchema)` to create a new message.
 */
export const LoginResponseSchema: GenMessage<LoginResponse> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 3);

/**
 * @generated from message service.auth.v1.LogoutRequest
 */
export type LogoutRequest = Message<"service.auth.v1.LogoutRequest"> & {
  /**
   * @generated from field: string session = 1;
   */
  session: string;
};

/**
 * Describes the message service.auth.v1.LogoutRequest.
 * Use `create(LogoutRequestSchema)` to create a new message.
 */
export const LogoutRequestSchema: GenMessage<LogoutRequest> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 4);

/**
 * @generated from message service.auth.v1.LogoutResponse
 */
export type LogoutResponse = Message<"service.auth.v1.LogoutResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message service.auth.v1.LogoutResponse.
 * Use `create(LogoutResponseSchema)` to create a new message.
 */
export const LogoutResponseSchema: GenMessage<LogoutResponse> = /*@__PURE__*/
  messageDesc(file_service_auth_v1_service, 5);

/**
 * @generated from enum service.auth.v1.AuthProvider
 */
export enum AuthProvider {
  /**
   * @generated from enum value: AUTH_PROVIDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: AUTH_PROVIDER_GITHUB = 1;
   */
  GITHUB = 1,
}

/**
 * Describes the enum service.auth.v1.AuthProvider.
 */
export const AuthProviderSchema: GenEnum<AuthProvider> = /*@__PURE__*/
  enumDesc(file_service_auth_v1_service, 0);

/**
 * @generated from service service.auth.v1.AuthService
 */
export const AuthService: GenService<{
  /**
   * @generated from rpc service.auth.v1.AuthService.GetAuthURL
   */
  getAuthURL: {
    methodKind: "unary";
    input: typeof GetAuthURLRequestSchema;
    output: typeof GetAuthURLResponseSchema;
  },
  /**
   * @generated from rpc service.auth.v1.AuthService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof LoginRequestSchema;
    output: typeof LoginResponseSchema;
  },
  /**
   * @generated from rpc service.auth.v1.AuthService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof LogoutRequestSchema;
    output: typeof LogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service_auth_v1_service, 0);

