// @generated by protoc-gen-connect-query v2.1.0 with parameter "target=ts,import_extension=none"
// @generated from file service/auth/v1/service.proto (package service.auth.v1, syntax proto3)
/* eslint-disable */

import { AuthService } from "./service_pb";

/**
 * @generated from rpc service.auth.v1.AuthService.GetAuthURL
 */
export const getAuthURL = AuthService.method.getAuthURL;

/**
 * @generated from rpc service.auth.v1.AuthService.Logout
 */
export const logout = AuthService.method.logout;
