// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/v1/identity_provider.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdentityProvider int32

const (
	IdentityProvider_IDENTITY_PROVIDER_UNSPECIFIED IdentityProvider = 0
	IdentityProvider_IDENTITY_PROVIDER_GITHUB      IdentityProvider = 1
)

// Enum value maps for IdentityProvider.
var (
	IdentityProvider_name = map[int32]string{
		0: "IDENTITY_PROVIDER_UNSPECIFIED",
		1: "IDENTITY_PROVIDER_GITHUB",
	}
	IdentityProvider_value = map[string]int32{
		"IDENTITY_PROVIDER_UNSPECIFIED": 0,
		"IDENTITY_PROVIDER_GITHUB":      1,
	}
)

func (x IdentityProvider) Enum() *IdentityProvider {
	p := new(IdentityProvider)
	*p = x
	return p
}

func (x IdentityProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IdentityProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_types_v1_identity_provider_proto_enumTypes[0].Descriptor()
}

func (IdentityProvider) Type() protoreflect.EnumType {
	return &file_types_v1_identity_provider_proto_enumTypes[0]
}

func (x IdentityProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IdentityProvider.Descriptor instead.
func (IdentityProvider) EnumDescriptor() ([]byte, []int) {
	return file_types_v1_identity_provider_proto_rawDescGZIP(), []int{0}
}

var File_types_v1_identity_provider_proto protoreflect.FileDescriptor

const file_types_v1_identity_provider_proto_rawDesc = "" +
	"\n" +
	" types/v1/identity_provider.proto\x12\btypes.v1*S\n" +
	"\x10IdentityProvider\x12!\n" +
	"\x1dIDENTITY_PROVIDER_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18IDENTITY_PROVIDER_GITHUB\x10\x01B6Z4github.com/gaesemo/tech-blog-api/go/types/v1;typesv1b\x06proto3"

var (
	file_types_v1_identity_provider_proto_rawDescOnce sync.Once
	file_types_v1_identity_provider_proto_rawDescData []byte
)

func file_types_v1_identity_provider_proto_rawDescGZIP() []byte {
	file_types_v1_identity_provider_proto_rawDescOnce.Do(func() {
		file_types_v1_identity_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_v1_identity_provider_proto_rawDesc), len(file_types_v1_identity_provider_proto_rawDesc)))
	})
	return file_types_v1_identity_provider_proto_rawDescData
}

var file_types_v1_identity_provider_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_types_v1_identity_provider_proto_goTypes = []any{
	(IdentityProvider)(0), // 0: types.v1.IdentityProvider
}
var file_types_v1_identity_provider_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_v1_identity_provider_proto_init() }
func file_types_v1_identity_provider_proto_init() {
	if File_types_v1_identity_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_v1_identity_provider_proto_rawDesc), len(file_types_v1_identity_provider_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_v1_identity_provider_proto_goTypes,
		DependencyIndexes: file_types_v1_identity_provider_proto_depIdxs,
		EnumInfos:         file_types_v1_identity_provider_proto_enumTypes,
	}.Build()
	File_types_v1_identity_provider_proto = out.File
	file_types_v1_identity_provider_proto_goTypes = nil
	file_types_v1_identity_provider_proto_depIdxs = nil
}
