// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: types/v1/post.proto

package typesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Likes         int64                  `protobuf:"varint,2,opt,name=likes,proto3" json:"likes,omitempty"`
	Views         int64                  `protobuf:"varint,3,opt,name=views,proto3" json:"views,omitempty"`
	Author        *User                  `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Content       *PostContent           `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,100,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_types_v1_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_types_v1_post_proto_rawDescGZIP(), []int{0}
}

func (x *Post) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Post) GetLikes() int64 {
	if x != nil {
		return x.Likes
	}
	return 0
}

func (x *Post) GetViews() int64 {
	if x != nil {
		return x.Views
	}
	return 0
}

func (x *Post) GetAuthor() *User {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Post) GetContent() *PostContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Post) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Post) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Post) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

type PostContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostContent) Reset() {
	*x = PostContent{}
	mi := &file_types_v1_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostContent) ProtoMessage() {}

func (x *PostContent) ProtoReflect() protoreflect.Message {
	mi := &file_types_v1_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostContent.ProtoReflect.Descriptor instead.
func (*PostContent) Descriptor() ([]byte, []int) {
	return file_types_v1_post_proto_rawDescGZIP(), []int{1}
}

func (x *PostContent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostContent) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_types_v1_post_proto protoreflect.FileDescriptor

const file_types_v1_post_proto_rawDesc = "" +
	"\n" +
	"\x13types/v1/post.proto\x12\btypes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x13types/v1/user.proto\"\xcc\x02\n" +
	"\x04Post\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05likes\x18\x02 \x01(\x03R\x05likes\x12\x14\n" +
	"\x05views\x18\x03 \x01(\x03R\x05views\x12&\n" +
	"\x06author\x18\x04 \x01(\v2\x0e.types.v1.UserR\x06author\x12/\n" +
	"\acontent\x18\x05 \x01(\v2\x15.types.v1.PostContentR\acontent\x129\n" +
	"\n" +
	"created_at\x18d \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18f \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"7\n" +
	"\vPostContent\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x02 \x01(\tR\x04bodyB1Z/github.com/gaesemo/blog-api/go/types/v1;typesv1b\x06proto3"

var (
	file_types_v1_post_proto_rawDescOnce sync.Once
	file_types_v1_post_proto_rawDescData []byte
)

func file_types_v1_post_proto_rawDescGZIP() []byte {
	file_types_v1_post_proto_rawDescOnce.Do(func() {
		file_types_v1_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_v1_post_proto_rawDesc), len(file_types_v1_post_proto_rawDesc)))
	})
	return file_types_v1_post_proto_rawDescData
}

var file_types_v1_post_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_types_v1_post_proto_goTypes = []any{
	(*Post)(nil),                  // 0: types.v1.Post
	(*PostContent)(nil),           // 1: types.v1.PostContent
	(*User)(nil),                  // 2: types.v1.User
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_types_v1_post_proto_depIdxs = []int32{
	2, // 0: types.v1.Post.author:type_name -> types.v1.User
	1, // 1: types.v1.Post.content:type_name -> types.v1.PostContent
	3, // 2: types.v1.Post.created_at:type_name -> google.protobuf.Timestamp
	3, // 3: types.v1.Post.updated_at:type_name -> google.protobuf.Timestamp
	3, // 4: types.v1.Post.deleted_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_types_v1_post_proto_init() }
func file_types_v1_post_proto_init() {
	if File_types_v1_post_proto != nil {
		return
	}
	file_types_v1_user_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_v1_post_proto_rawDesc), len(file_types_v1_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_v1_post_proto_goTypes,
		DependencyIndexes: file_types_v1_post_proto_depIdxs,
		MessageInfos:      file_types_v1_post_proto_msgTypes,
	}.Build()
	File_types_v1_post_proto = out.File
	file_types_v1_post_proto_goTypes = nil
	file_types_v1_post_proto_depIdxs = nil
}
