// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file service/user/v1/service.proto (package service.user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { User } from "../../../types/v1/user_pb";
import { file_types_v1_user } from "../../../types/v1/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/user/v1/service.proto.
 */
export const file_service_user_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1zZXJ2aWNlL3VzZXIvdjEvc2VydmljZS5wcm90bxIPc2VydmljZS51c2VyLnYxIg4KDEdldE1lUmVxdWVzdCItCg1HZXRNZVJlc3BvbnNlEhwKBHVzZXIYASABKAsyDi50eXBlcy52MS5Vc2VyIiAKEkdldFVzZXJCeUlkUmVxdWVzdBIKCgJpZBgBIAEoAyIzChNHZXRVc2VyQnlJZFJlc3BvbnNlEhwKBHVzZXIYASABKAsyDi50eXBlcy52MS5Vc2VyMrMBCgtVc2VyU2VydmljZRJICgVHZXRNZRIdLnNlcnZpY2UudXNlci52MS5HZXRNZVJlcXVlc3QaHi5zZXJ2aWNlLnVzZXIudjEuR2V0TWVSZXNwb25zZSIAEloKC0dldFVzZXJCeUlkEiMuc2VydmljZS51c2VyLnYxLkdldFVzZXJCeUlkUmVxdWVzdBokLnNlcnZpY2UudXNlci52MS5HZXRVc2VyQnlJZFJlc3BvbnNlIgBCPFo6Z2l0aHViLmNvbS9nYWVzZW1vL3RlY2gtYmxvZy1hcGkvZ28vc2VydmljZS91c2VyL3YxO3VzZXJ2MWIGcHJvdG8z", [file_types_v1_user]);

/**
 * @generated from message service.user.v1.GetMeRequest
 */
export type GetMeRequest = Message<"service.user.v1.GetMeRequest"> & {
};

/**
 * Describes the message service.user.v1.GetMeRequest.
 * Use `create(GetMeRequestSchema)` to create a new message.
 */
export const GetMeRequestSchema: GenMessage<GetMeRequest> = /*@__PURE__*/
  messageDesc(file_service_user_v1_service, 0);

/**
 * @generated from message service.user.v1.GetMeResponse
 */
export type GetMeResponse = Message<"service.user.v1.GetMeResponse"> & {
  /**
   * @generated from field: types.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message service.user.v1.GetMeResponse.
 * Use `create(GetMeResponseSchema)` to create a new message.
 */
export const GetMeResponseSchema: GenMessage<GetMeResponse> = /*@__PURE__*/
  messageDesc(file_service_user_v1_service, 1);

/**
 * @generated from message service.user.v1.GetUserByIdRequest
 */
export type GetUserByIdRequest = Message<"service.user.v1.GetUserByIdRequest"> & {
  /**
   * required
   *
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message service.user.v1.GetUserByIdRequest.
 * Use `create(GetUserByIdRequestSchema)` to create a new message.
 */
export const GetUserByIdRequestSchema: GenMessage<GetUserByIdRequest> = /*@__PURE__*/
  messageDesc(file_service_user_v1_service, 2);

/**
 * @generated from message service.user.v1.GetUserByIdResponse
 */
export type GetUserByIdResponse = Message<"service.user.v1.GetUserByIdResponse"> & {
  /**
   * @generated from field: types.v1.User user = 1;
   */
  user?: User;
};

/**
 * Describes the message service.user.v1.GetUserByIdResponse.
 * Use `create(GetUserByIdResponseSchema)` to create a new message.
 */
export const GetUserByIdResponseSchema: GenMessage<GetUserByIdResponse> = /*@__PURE__*/
  messageDesc(file_service_user_v1_service, 3);

/**
 * @generated from service service.user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc service.user.v1.UserService.GetMe
   */
  getMe: {
    methodKind: "unary";
    input: typeof GetMeRequestSchema;
    output: typeof GetMeResponseSchema;
  },
  /**
   * @generated from rpc service.user.v1.UserService.GetUserById
   */
  getUserById: {
    methodKind: "unary";
    input: typeof GetUserByIdRequestSchema;
    output: typeof GetUserByIdResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service_user_v1_service, 0);

