// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file service/user/v1/service.proto (package service.user.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { UserGrade } from "../../../types/v1/user_pb";
import { file_types_v1_user } from "../../../types/v1/user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/user/v1/service.proto.
 */
export const file_service_user_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1zZXJ2aWNlL3VzZXIvdjEvc2VydmljZS5wcm90bxIPc2VydmljZS51c2VyLnYxIjoKEUdldFByb2ZpbGVSZXF1ZXN0EhQKDGFjY2Vzc190b2tlbhgBIAEoCRIPCgdzZXNzaW9uGAIgASgJInQKEkdldFByb2ZpbGVSZXNwb25zZRIQCgh1c2VybmFtZRgBIAEoCRINCgVlbWFpbBgCIAEoCRIZChFwcm9maWxlX2ltYWdlX3VybBgDIAEoCRIiCgVncmFkZRgEIAEoDjITLnR5cGVzLnYxLlVzZXJHcmFkZTJmCgtVc2VyU2VydmljZRJXCgpHZXRQcm9maWxlEiIuc2VydmljZS51c2VyLnYxLkdldFByb2ZpbGVSZXF1ZXN0GiMuc2VydmljZS51c2VyLnYxLkdldFByb2ZpbGVSZXNwb25zZSIAQhhaFnNlcnZpY2UvdXNlci92MTt1c2VydjFiBnByb3RvMw", [file_types_v1_user]);

/**
 * @generated from message service.user.v1.GetProfileRequest
 */
export type GetProfileRequest = Message<"service.user.v1.GetProfileRequest"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;

  /**
   * @generated from field: string session = 2;
   */
  session: string;
};

/**
 * Describes the message service.user.v1.GetProfileRequest.
 * Use `create(GetProfileRequestSchema)` to create a new message.
 */
export const GetProfileRequestSchema: GenMessage<GetProfileRequest> = /*@__PURE__*/
  messageDesc(file_service_user_v1_service, 0);

/**
 * @generated from message service.user.v1.GetProfileResponse
 */
export type GetProfileResponse = Message<"service.user.v1.GetProfileResponse"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string profile_image_url = 3;
   */
  profileImageUrl: string;

  /**
   * @generated from field: types.v1.UserGrade grade = 4;
   */
  grade: UserGrade;
};

/**
 * Describes the message service.user.v1.GetProfileResponse.
 * Use `create(GetProfileResponseSchema)` to create a new message.
 */
export const GetProfileResponseSchema: GenMessage<GetProfileResponse> = /*@__PURE__*/
  messageDesc(file_service_user_v1_service, 1);

/**
 * @generated from service service.user.v1.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc service.user.v1.UserService.GetProfile
   */
  getProfile: {
    methodKind: "unary";
    input: typeof GetProfileRequestSchema;
    output: typeof GetProfileResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service_user_v1_service, 0);

