// @generated by protoc-gen-connect-query v2.1.0 with parameter "target=ts,import_extension=none"
// @generated from file service/user/v1/service.proto (package service.user.v1, syntax proto3)
/* eslint-disable */

import { UserService } from "./service_pb";

/**
 * @generated from rpc service.user.v1.UserService.GetMe
 */
export const getMe = UserService.method.getMe;

/**
 * @generated from rpc service.user.v1.UserService.GetUserById
 */
export const getUserById = UserService.method.getUserById;
