// @generated by protoc-gen-connect-query v2.1.0 with parameter "target=ts,import_extension=none"
// @generated from file service/user/v1/service.proto (package service.user.v1, syntax proto3)
/* eslint-disable */

import { UserService } from "./service_pb";

/**
 * @generated from rpc service.user.v1.UserService.GetProfile
 */
export const getProfile = UserService.method.getProfile;
