// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service/user/v1/service.proto

package userv1

import (
	v1 "github.com/gaesemo/tech-blog-api/go/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_service_user_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_service_user_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetProfileRequest) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

type GetProfileResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Email            string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	AvatarUrl        string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	Grade            v1.UserGrade           `protobuf:"varint,10,opt,name=grade,proto3,enum=types.v1.UserGrade" json:"grade,omitempty"`
	IdentityProvider v1.IdentityProvider    `protobuf:"varint,11,opt,name=identity_provider,json=identityProvider,proto3,enum=types.v1.IdentityProvider" json:"identity_provider,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_service_user_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_service_user_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetProfileResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetProfileResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetProfileResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *GetProfileResponse) GetGrade() v1.UserGrade {
	if x != nil {
		return x.Grade
	}
	return v1.UserGrade(0)
}

func (x *GetProfileResponse) GetIdentityProvider() v1.IdentityProvider {
	if x != nil {
		return x.IdentityProvider
	}
	return v1.IdentityProvider(0)
}

var File_service_user_v1_service_proto protoreflect.FileDescriptor

const file_service_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dservice/user/v1/service.proto\x12\x0fservice.user.v1\x1a\x13types/v1/user.proto\x1a types/v1/identity_provider.proto\"P\n" +
	"\x11GetProfileRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession\"\xd9\x01\n" +
	"\x12GetProfileResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12)\n" +
	"\x05grade\x18\n" +
	" \x01(\x0e2\x13.types.v1.UserGradeR\x05grade\x12G\n" +
	"\x11identity_provider\x18\v \x01(\x0e2\x1a.types.v1.IdentityProviderR\x10identityProvider2f\n" +
	"\vUserService\x12W\n" +
	"\n" +
	"GetProfile\x12\".service.user.v1.GetProfileRequest\x1a#.service.user.v1.GetProfileResponse\"\x00B<Z:github.com/gaesemo/tech-blog-api/go/service/user/v1;userv1b\x06proto3"

var (
	file_service_user_v1_service_proto_rawDescOnce sync.Once
	file_service_user_v1_service_proto_rawDescData []byte
)

func file_service_user_v1_service_proto_rawDescGZIP() []byte {
	file_service_user_v1_service_proto_rawDescOnce.Do(func() {
		file_service_user_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_user_v1_service_proto_rawDesc), len(file_service_user_v1_service_proto_rawDesc)))
	})
	return file_service_user_v1_service_proto_rawDescData
}

var file_service_user_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_service_user_v1_service_proto_goTypes = []any{
	(*GetProfileRequest)(nil),  // 0: service.user.v1.GetProfileRequest
	(*GetProfileResponse)(nil), // 1: service.user.v1.GetProfileResponse
	(v1.UserGrade)(0),          // 2: types.v1.UserGrade
	(v1.IdentityProvider)(0),   // 3: types.v1.IdentityProvider
}
var file_service_user_v1_service_proto_depIdxs = []int32{
	2, // 0: service.user.v1.GetProfileResponse.grade:type_name -> types.v1.UserGrade
	3, // 1: service.user.v1.GetProfileResponse.identity_provider:type_name -> types.v1.IdentityProvider
	0, // 2: service.user.v1.UserService.GetProfile:input_type -> service.user.v1.GetProfileRequest
	1, // 3: service.user.v1.UserService.GetProfile:output_type -> service.user.v1.GetProfileResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_user_v1_service_proto_init() }
func file_service_user_v1_service_proto_init() {
	if File_service_user_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_user_v1_service_proto_rawDesc), len(file_service_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_v1_service_proto_goTypes,
		DependencyIndexes: file_service_user_v1_service_proto_depIdxs,
		MessageInfos:      file_service_user_v1_service_proto_msgTypes,
	}.Build()
	File_service_user_v1_service_proto = out.File
	file_service_user_v1_service_proto_goTypes = nil
	file_service_user_v1_service_proto_depIdxs = nil
}
