// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service/user/v1/service.proto

package userv1

import (
	v1 "github.com/gaesemo/blog-api/go/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeRequest) Reset() {
	*x = GetMeRequest{}
	mi := &file_service_user_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeRequest) ProtoMessage() {}

func (x *GetMeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeRequest.ProtoReflect.Descriptor instead.
func (*GetMeRequest) Descriptor() ([]byte, []int) {
	return file_service_user_v1_service_proto_rawDescGZIP(), []int{0}
}

type GetMeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeResponse) Reset() {
	*x = GetMeResponse{}
	mi := &file_service_user_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeResponse) ProtoMessage() {}

func (x *GetMeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeResponse.ProtoReflect.Descriptor instead.
func (*GetMeResponse) Descriptor() ([]byte, []int) {
	return file_service_user_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetMeResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserByIdRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// required
	Id            int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdRequest) Reset() {
	*x = GetUserByIdRequest{}
	mi := &file_service_user_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdRequest) ProtoMessage() {}

func (x *GetUserByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByIdRequest) Descriptor() ([]byte, []int) {
	return file_service_user_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByIdRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *v1.User               `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByIdResponse) Reset() {
	*x = GetUserByIdResponse{}
	mi := &file_service_user_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByIdResponse) ProtoMessage() {}

func (x *GetUserByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_user_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByIdResponse) Descriptor() ([]byte, []int) {
	return file_service_user_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByIdResponse) GetUser() *v1.User {
	if x != nil {
		return x.User
	}
	return nil
}

var File_service_user_v1_service_proto protoreflect.FileDescriptor

const file_service_user_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dservice/user/v1/service.proto\x12\x0fservice.user.v1\x1a\x13types/v1/user.proto\"\x0e\n" +
	"\fGetMeRequest\"3\n" +
	"\rGetMeResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.types.v1.UserR\x04user\"$\n" +
	"\x12GetUserByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"9\n" +
	"\x13GetUserByIdResponse\x12\"\n" +
	"\x04user\x18\x01 \x01(\v2\x0e.types.v1.UserR\x04user2\xb3\x01\n" +
	"\vUserService\x12H\n" +
	"\x05GetMe\x12\x1d.service.user.v1.GetMeRequest\x1a\x1e.service.user.v1.GetMeResponse\"\x00\x12Z\n" +
	"\vGetUserById\x12#.service.user.v1.GetUserByIdRequest\x1a$.service.user.v1.GetUserByIdResponse\"\x00B7Z5github.com/gaesemo/blog-api/go/service/user/v1;userv1b\x06proto3"

var (
	file_service_user_v1_service_proto_rawDescOnce sync.Once
	file_service_user_v1_service_proto_rawDescData []byte
)

func file_service_user_v1_service_proto_rawDescGZIP() []byte {
	file_service_user_v1_service_proto_rawDescOnce.Do(func() {
		file_service_user_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_user_v1_service_proto_rawDesc), len(file_service_user_v1_service_proto_rawDesc)))
	})
	return file_service_user_v1_service_proto_rawDescData
}

var file_service_user_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_user_v1_service_proto_goTypes = []any{
	(*GetMeRequest)(nil),        // 0: service.user.v1.GetMeRequest
	(*GetMeResponse)(nil),       // 1: service.user.v1.GetMeResponse
	(*GetUserByIdRequest)(nil),  // 2: service.user.v1.GetUserByIdRequest
	(*GetUserByIdResponse)(nil), // 3: service.user.v1.GetUserByIdResponse
	(*v1.User)(nil),             // 4: types.v1.User
}
var file_service_user_v1_service_proto_depIdxs = []int32{
	4, // 0: service.user.v1.GetMeResponse.user:type_name -> types.v1.User
	4, // 1: service.user.v1.GetUserByIdResponse.user:type_name -> types.v1.User
	0, // 2: service.user.v1.UserService.GetMe:input_type -> service.user.v1.GetMeRequest
	2, // 3: service.user.v1.UserService.GetUserById:input_type -> service.user.v1.GetUserByIdRequest
	1, // 4: service.user.v1.UserService.GetMe:output_type -> service.user.v1.GetMeResponse
	3, // 5: service.user.v1.UserService.GetUserById:output_type -> service.user.v1.GetUserByIdResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_user_v1_service_proto_init() }
func file_service_user_v1_service_proto_init() {
	if File_service_user_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_user_v1_service_proto_rawDesc), len(file_service_user_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_user_v1_service_proto_goTypes,
		DependencyIndexes: file_service_user_v1_service_proto_depIdxs,
		MessageInfos:      file_service_user_v1_service_proto_msgTypes,
	}.Build()
	File_service_user_v1_service_proto = out.File
	file_service_user_v1_service_proto_goTypes = nil
	file_service_user_v1_service_proto_depIdxs = nil
}
