// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service/post/v1/service.proto

package postv1

import (
	v1 "github.com/gaesemo/blog-api/go/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostContent   *v1.PostContent        `protobuf:"bytes,1,opt,name=post_content,json=postContent,proto3" json:"post_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_service_post_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRequest) GetPostContent() *v1.PostContent {
	if x != nil {
		return x.PostContent
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *v1.Post               `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_service_post_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *CreateResponse) GetPost() *v1.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        *v1.Cursor             `protobuf:"bytes,100,opt,name=cursor,proto3,oneof" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_service_post_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListRequest) GetCursor() *v1.Cursor {
	if x != nil {
		return x.Cursor
	}
	return nil
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*v1.Post             `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	Next          *v1.Cursor             `protobuf:"bytes,100,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_service_post_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *ListResponse) GetPosts() []*v1.Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *ListResponse) GetNext() *v1.Cursor {
	if x != nil {
		return x.Next
	}
	return nil
}

type DetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailRequest) Reset() {
	*x = DetailRequest{}
	mi := &file_service_post_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailRequest) ProtoMessage() {}

func (x *DetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailRequest.ProtoReflect.Descriptor instead.
func (*DetailRequest) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *DetailRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *v1.Post               `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetailResponse) Reset() {
	*x = DetailResponse{}
	mi := &file_service_post_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetailResponse) ProtoMessage() {}

func (x *DetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetailResponse.ProtoReflect.Descriptor instead.
func (*DetailResponse) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *DetailResponse) GetPost() *v1.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *v1.Post               `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_service_post_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateRequest) GetPost() *v1.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_service_post_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Post          *v1.Post               `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_service_post_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteRequest) GetPost() *v1.Post {
	if x != nil {
		return x.Post
	}
	return nil
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_service_post_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_post_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_service_post_v1_service_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_service_post_v1_service_proto protoreflect.FileDescriptor

const file_service_post_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dservice/post/v1/service.proto\x12\x0fservice.post.v1\x1a\x13types/v1/post.proto\x1a\x15types/v1/cursor.proto\"I\n" +
	"\rCreateRequest\x128\n" +
	"\fpost_content\x18\x01 \x01(\v2\x15.types.v1.PostContentR\vpostContent\"4\n" +
	"\x0eCreateResponse\x12\"\n" +
	"\x04post\x18\x01 \x01(\v2\x0e.types.v1.PostR\x04post\"G\n" +
	"\vListRequest\x12-\n" +
	"\x06cursor\x18d \x01(\v2\x10.types.v1.CursorH\x00R\x06cursor\x88\x01\x01B\t\n" +
	"\a_cursor\"Z\n" +
	"\fListResponse\x12$\n" +
	"\x05posts\x18\x01 \x03(\v2\x0e.types.v1.PostR\x05posts\x12$\n" +
	"\x04next\x18d \x01(\v2\x10.types.v1.CursorR\x04next\"\x1f\n" +
	"\rDetailRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"4\n" +
	"\x0eDetailResponse\x12\"\n" +
	"\x04post\x18\x01 \x01(\v2\x0e.types.v1.PostR\x04post\"3\n" +
	"\rUpdateRequest\x12\"\n" +
	"\x04post\x18\x01 \x01(\v2\x0e.types.v1.PostR\x04post\"*\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\rDeleteRequest\x12\"\n" +
	"\x04post\x18\x01 \x01(\v2\x0e.types.v1.PostR\x04post\"*\n" +
	"\x0eDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x88\x03\n" +
	"\vPostService\x12K\n" +
	"\x06Create\x12\x1e.service.post.v1.CreateRequest\x1a\x1f.service.post.v1.CreateResponse\"\x00\x12E\n" +
	"\x04List\x12\x1c.service.post.v1.ListRequest\x1a\x1d.service.post.v1.ListResponse\"\x00\x12K\n" +
	"\x06Detail\x12\x1e.service.post.v1.DetailRequest\x1a\x1f.service.post.v1.DetailResponse\"\x00\x12K\n" +
	"\x06Update\x12\x1e.service.post.v1.UpdateRequest\x1a\x1f.service.post.v1.UpdateResponse\"\x00\x12K\n" +
	"\x06Delete\x12\x1e.service.post.v1.DeleteRequest\x1a\x1f.service.post.v1.DeleteResponse\"\x00B7Z5github.com/gaesemo/blog-api/go/service/post/v1;postv1b\x06proto3"

var (
	file_service_post_v1_service_proto_rawDescOnce sync.Once
	file_service_post_v1_service_proto_rawDescData []byte
)

func file_service_post_v1_service_proto_rawDescGZIP() []byte {
	file_service_post_v1_service_proto_rawDescOnce.Do(func() {
		file_service_post_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_post_v1_service_proto_rawDesc), len(file_service_post_v1_service_proto_rawDesc)))
	})
	return file_service_post_v1_service_proto_rawDescData
}

var file_service_post_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_post_v1_service_proto_goTypes = []any{
	(*CreateRequest)(nil),  // 0: service.post.v1.CreateRequest
	(*CreateResponse)(nil), // 1: service.post.v1.CreateResponse
	(*ListRequest)(nil),    // 2: service.post.v1.ListRequest
	(*ListResponse)(nil),   // 3: service.post.v1.ListResponse
	(*DetailRequest)(nil),  // 4: service.post.v1.DetailRequest
	(*DetailResponse)(nil), // 5: service.post.v1.DetailResponse
	(*UpdateRequest)(nil),  // 6: service.post.v1.UpdateRequest
	(*UpdateResponse)(nil), // 7: service.post.v1.UpdateResponse
	(*DeleteRequest)(nil),  // 8: service.post.v1.DeleteRequest
	(*DeleteResponse)(nil), // 9: service.post.v1.DeleteResponse
	(*v1.PostContent)(nil), // 10: types.v1.PostContent
	(*v1.Post)(nil),        // 11: types.v1.Post
	(*v1.Cursor)(nil),      // 12: types.v1.Cursor
}
var file_service_post_v1_service_proto_depIdxs = []int32{
	10, // 0: service.post.v1.CreateRequest.post_content:type_name -> types.v1.PostContent
	11, // 1: service.post.v1.CreateResponse.post:type_name -> types.v1.Post
	12, // 2: service.post.v1.ListRequest.cursor:type_name -> types.v1.Cursor
	11, // 3: service.post.v1.ListResponse.posts:type_name -> types.v1.Post
	12, // 4: service.post.v1.ListResponse.next:type_name -> types.v1.Cursor
	11, // 5: service.post.v1.DetailResponse.post:type_name -> types.v1.Post
	11, // 6: service.post.v1.UpdateRequest.post:type_name -> types.v1.Post
	11, // 7: service.post.v1.DeleteRequest.post:type_name -> types.v1.Post
	0,  // 8: service.post.v1.PostService.Create:input_type -> service.post.v1.CreateRequest
	2,  // 9: service.post.v1.PostService.List:input_type -> service.post.v1.ListRequest
	4,  // 10: service.post.v1.PostService.Detail:input_type -> service.post.v1.DetailRequest
	6,  // 11: service.post.v1.PostService.Update:input_type -> service.post.v1.UpdateRequest
	8,  // 12: service.post.v1.PostService.Delete:input_type -> service.post.v1.DeleteRequest
	1,  // 13: service.post.v1.PostService.Create:output_type -> service.post.v1.CreateResponse
	3,  // 14: service.post.v1.PostService.List:output_type -> service.post.v1.ListResponse
	5,  // 15: service.post.v1.PostService.Detail:output_type -> service.post.v1.DetailResponse
	7,  // 16: service.post.v1.PostService.Update:output_type -> service.post.v1.UpdateResponse
	9,  // 17: service.post.v1.PostService.Delete:output_type -> service.post.v1.DeleteResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_service_post_v1_service_proto_init() }
func file_service_post_v1_service_proto_init() {
	if File_service_post_v1_service_proto != nil {
		return
	}
	file_service_post_v1_service_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_post_v1_service_proto_rawDesc), len(file_service_post_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_post_v1_service_proto_goTypes,
		DependencyIndexes: file_service_post_v1_service_proto_depIdxs,
		MessageInfos:      file_service_post_v1_service_proto_msgTypes,
	}.Build()
	File_service_post_v1_service_proto = out.File
	file_service_post_v1_service_proto_goTypes = nil
	file_service_post_v1_service_proto_depIdxs = nil
}
