// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file service/post/v1/service.proto (package service.post.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Post, PostContent } from "../../../types/v1/post_pb";
import { file_types_v1_post } from "../../../types/v1/post_pb";
import type { Cursor } from "../../../types/v1/cursor_pb";
import { file_types_v1_cursor } from "../../../types/v1/cursor_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service/post/v1/service.proto.
 */
export const file_service_post_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch1zZXJ2aWNlL3Bvc3QvdjEvc2VydmljZS5wcm90bxIPc2VydmljZS5wb3N0LnYxIjwKDUNyZWF0ZVJlcXVlc3QSKwoMcG9zdF9jb250ZW50GAEgASgLMhUudHlwZXMudjEuUG9zdENvbnRlbnQiLgoOQ3JlYXRlUmVzcG9uc2USHAoEcG9zdBgBIAEoCzIOLnR5cGVzLnYxLlBvc3QiPwoLTGlzdFJlcXVlc3QSJQoGY3Vyb3NyGGQgASgLMhAudHlwZXMudjEuQ3Vyc29ySACIAQFCCQoHX2N1cm9zciJNCgxMaXN0UmVzcG9uc2USHQoFcG9zdHMYASADKAsyDi50eXBlcy52MS5Qb3N0Eh4KBG5leHQYZCABKAsyEC50eXBlcy52MS5DdXJzb3IiGwoNRGV0YWlsUmVxdWVzdBIKCgJpZBgBIAEoAyIuCg5EZXRhaWxSZXNwb25zZRIcCgRwb3N0GAEgASgLMg4udHlwZXMudjEuUG9zdCI8Cg1VcGRhdGVSZXF1ZXN0EgoKAmlkGAEgASgDEg0KBXRpdGxlGAIgASgJEhAKCG1hcmtkb3duGAMgASgJIhAKDlVwZGF0ZVJlc3BvbnNlIhsKDURlbGV0ZVJlcXVlc3QSCgoCaWQYASABKAMiEAoORGVsZXRlUmVzcG9uc2UyiAMKC1Bvc3RTZXJ2aWNlEksKBkNyZWF0ZRIeLnNlcnZpY2UucG9zdC52MS5DcmVhdGVSZXF1ZXN0Gh8uc2VydmljZS5wb3N0LnYxLkNyZWF0ZVJlc3BvbnNlIgASRQoETGlzdBIcLnNlcnZpY2UucG9zdC52MS5MaXN0UmVxdWVzdBodLnNlcnZpY2UucG9zdC52MS5MaXN0UmVzcG9uc2UiABJLCgZEZXRhaWwSHi5zZXJ2aWNlLnBvc3QudjEuRGV0YWlsUmVxdWVzdBofLnNlcnZpY2UucG9zdC52MS5EZXRhaWxSZXNwb25zZSIAEksKBlVwZGF0ZRIeLnNlcnZpY2UucG9zdC52MS5VcGRhdGVSZXF1ZXN0Gh8uc2VydmljZS5wb3N0LnYxLlVwZGF0ZVJlc3BvbnNlIgASSwoGRGVsZXRlEh4uc2VydmljZS5wb3N0LnYxLkRlbGV0ZVJlcXVlc3QaHy5zZXJ2aWNlLnBvc3QudjEuRGVsZXRlUmVzcG9uc2UiAEI3WjVnaXRodWIuY29tL2dhZXNlbW8vYmxvZy1hcGkvZ28vc2VydmljZS9wb3N0L3YxO3Bvc3R2MWIGcHJvdG8z", [file_types_v1_post, file_types_v1_cursor]);

/**
 * @generated from message service.post.v1.CreateRequest
 */
export type CreateRequest = Message<"service.post.v1.CreateRequest"> & {
  /**
   * @generated from field: types.v1.PostContent post_content = 1;
   */
  postContent?: PostContent;
};

/**
 * Describes the message service.post.v1.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 0);

/**
 * @generated from message service.post.v1.CreateResponse
 */
export type CreateResponse = Message<"service.post.v1.CreateResponse"> & {
  /**
   * @generated from field: types.v1.Post post = 1;
   */
  post?: Post;
};

/**
 * Describes the message service.post.v1.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 1);

/**
 * @generated from message service.post.v1.ListRequest
 */
export type ListRequest = Message<"service.post.v1.ListRequest"> & {
  /**
   * @generated from field: optional types.v1.Cursor curosr = 100;
   */
  curosr?: Cursor;
};

/**
 * Describes the message service.post.v1.ListRequest.
 * Use `create(ListRequestSchema)` to create a new message.
 */
export const ListRequestSchema: GenMessage<ListRequest> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 2);

/**
 * @generated from message service.post.v1.ListResponse
 */
export type ListResponse = Message<"service.post.v1.ListResponse"> & {
  /**
   * @generated from field: repeated types.v1.Post posts = 1;
   */
  posts: Post[];

  /**
   * @generated from field: types.v1.Cursor next = 100;
   */
  next?: Cursor;
};

/**
 * Describes the message service.post.v1.ListResponse.
 * Use `create(ListResponseSchema)` to create a new message.
 */
export const ListResponseSchema: GenMessage<ListResponse> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 3);

/**
 * @generated from message service.post.v1.DetailRequest
 */
export type DetailRequest = Message<"service.post.v1.DetailRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message service.post.v1.DetailRequest.
 * Use `create(DetailRequestSchema)` to create a new message.
 */
export const DetailRequestSchema: GenMessage<DetailRequest> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 4);

/**
 * @generated from message service.post.v1.DetailResponse
 */
export type DetailResponse = Message<"service.post.v1.DetailResponse"> & {
  /**
   * @generated from field: types.v1.Post post = 1;
   */
  post?: Post;
};

/**
 * Describes the message service.post.v1.DetailResponse.
 * Use `create(DetailResponseSchema)` to create a new message.
 */
export const DetailResponseSchema: GenMessage<DetailResponse> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 5);

/**
 * @generated from message service.post.v1.UpdateRequest
 */
export type UpdateRequest = Message<"service.post.v1.UpdateRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string markdown = 3;
   */
  markdown: string;
};

/**
 * Describes the message service.post.v1.UpdateRequest.
 * Use `create(UpdateRequestSchema)` to create a new message.
 */
export const UpdateRequestSchema: GenMessage<UpdateRequest> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 6);

/**
 * @generated from message service.post.v1.UpdateResponse
 */
export type UpdateResponse = Message<"service.post.v1.UpdateResponse"> & {
};

/**
 * Describes the message service.post.v1.UpdateResponse.
 * Use `create(UpdateResponseSchema)` to create a new message.
 */
export const UpdateResponseSchema: GenMessage<UpdateResponse> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 7);

/**
 * @generated from message service.post.v1.DeleteRequest
 */
export type DeleteRequest = Message<"service.post.v1.DeleteRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message service.post.v1.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 8);

/**
 * @generated from message service.post.v1.DeleteResponse
 */
export type DeleteResponse = Message<"service.post.v1.DeleteResponse"> & {
};

/**
 * Describes the message service.post.v1.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse> = /*@__PURE__*/
  messageDesc(file_service_post_v1_service, 9);

/**
 * @generated from service service.post.v1.PostService
 */
export const PostService: GenService<{
  /**
   * @generated from rpc service.post.v1.PostService.Create
   */
  create: {
    methodKind: "unary";
    input: typeof CreateRequestSchema;
    output: typeof CreateResponseSchema;
  },
  /**
   * @generated from rpc service.post.v1.PostService.List
   */
  list: {
    methodKind: "unary";
    input: typeof ListRequestSchema;
    output: typeof ListResponseSchema;
  },
  /**
   * rpc Search(SearchRequest) returns (SearchResponse) {} // TODO: define the concept of search.
   *
   * @generated from rpc service.post.v1.PostService.Detail
   */
  detail: {
    methodKind: "unary";
    input: typeof DetailRequestSchema;
    output: typeof DetailResponseSchema;
  },
  /**
   * @generated from rpc service.post.v1.PostService.Update
   */
  update: {
    methodKind: "unary";
    input: typeof UpdateRequestSchema;
    output: typeof UpdateResponseSchema;
  },
  /**
   * @generated from rpc service.post.v1.PostService.Delete
   */
  delete: {
    methodKind: "unary";
    input: typeof DeleteRequestSchema;
    output: typeof DeleteResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service_post_v1_service, 0);

