// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/identity_provider.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file types/v1/identity_provider.proto.
 */
export const file_types_v1_identity_provider: GenFile = /*@__PURE__*/
  fileDesc("CiB0eXBlcy92MS9pZGVudGl0eV9wcm92aWRlci5wcm90bxIIdHlwZXMudjEqUwoQSWRlbnRpdHlQcm92aWRlchIhCh1JREVOVElUWV9QUk9WSURFUl9VTlNQRUNJRklFRBAAEhwKGElERU5USVRZX1BST1ZJREVSX0dJVEhVQhABQjFaL2dpdGh1Yi5jb20vZ2Flc2Vtby9ibG9nLWFwaS9nby90eXBlcy92MTt0eXBlc3YxYgZwcm90bzM");

/**
 * @generated from enum types.v1.IdentityProvider
 */
export enum IdentityProvider {
  /**
   * @generated from enum value: IDENTITY_PROVIDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: IDENTITY_PROVIDER_GITHUB = 1;
   */
  GITHUB = 1,
}

/**
 * Describes the enum types.v1.IdentityProvider.
 */
export const IdentityProviderSchema: GenEnum<IdentityProvider> = /*@__PURE__*/
  enumDesc(file_types_v1_identity_provider, 0);

