// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/post.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { User } from "./user_pb";
import { file_types_v1_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/post.proto.
 */
export const file_types_v1_post: GenFile = /*@__PURE__*/
  fileDesc("ChN0eXBlcy92MS9wb3N0LnByb3RvEgh0eXBlcy52MSKIAgoEUG9zdBIKCgJpZBgBIAEoAxINCgVsaWtlcxgCIAEoAxINCgV2aWV3cxgDIAEoAxIeCgZhdXRob3IYBCABKAsyDi50eXBlcy52MS5Vc2VyEiYKB2NvbnRlbnQYBSABKAsyFS50eXBlcy52MS5Qb3N0Q29udGVudBIuCgpjcmVhdGVkX2F0GGQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GGUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgpkZWxldGVkX2F0GGYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCIqCgtQb3N0Q29udGVudBINCgV0aXRsZRgBIAEoCRIMCgRib2R5GAIgASgJQjFaL2dpdGh1Yi5jb20vZ2Flc2Vtby9ibG9nLWFwaS9nby90eXBlcy92MTt0eXBlc3YxYgZwcm90bzM", [file_google_protobuf_timestamp, file_types_v1_user]);

/**
 * @generated from message types.v1.Post
 */
export type Post = Message<"types.v1.Post"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 likes = 2;
   */
  likes: bigint;

  /**
   * @generated from field: int64 views = 3;
   */
  views: bigint;

  /**
   * @generated from field: types.v1.User author = 4;
   */
  author?: User;

  /**
   * @generated from field: types.v1.PostContent content = 5;
   */
  content?: PostContent;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 100;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 101;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 102;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message types.v1.Post.
 * Use `create(PostSchema)` to create a new message.
 */
export const PostSchema: GenMessage<Post> = /*@__PURE__*/
  messageDesc(file_types_v1_post, 0);

/**
 * @generated from message types.v1.PostContent
 */
export type PostContent = Message<"types.v1.PostContent"> & {
  /**
   * @generated from field: string title = 1;
   */
  title: string;

  /**
   * @generated from field: string body = 2;
   */
  body: string;
};

/**
 * Describes the message types.v1.PostContent.
 * Use `create(PostContentSchema)` to create a new message.
 */
export const PostContentSchema: GenMessage<PostContent> = /*@__PURE__*/
  messageDesc(file_types_v1_post, 1);

