// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/user.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { IdentityProvider } from "./identity_provider_pb";
import { file_types_v1_identity_provider } from "./identity_provider_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/user.proto.
 */
export const file_types_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChN0eXBlcy92MS91c2VyLnByb3RvEgh0eXBlcy52MSLwAQoEVXNlchIKCgJpZBgBIAEoBBIQCgh1c2VybmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRISCgphdmF0YXJfdXJsGAQgASgJEhAKCGFib3V0X21lGAUgASgJEjUKEWlkZW50aXR5X3Byb3ZpZGVyGAYgASgOMhoudHlwZXMudjEuSWRlbnRpdHlQcm92aWRlchIuCgpjcmVhdGVkX2F0GGQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GGUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEI2WjRnaXRodWIuY29tL2dhZXNlbW8vdGVjaC1ibG9nLWFwaS9nby90eXBlcy92MTt0eXBlc3YxYgZwcm90bzM", [file_google_protobuf_timestamp, file_types_v1_identity_provider]);

/**
 * @generated from message types.v1.User
 */
export type User = Message<"types.v1.User"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string avatar_url = 4;
   */
  avatarUrl: string;

  /**
   * @generated from field: string about_me = 5;
   */
  aboutMe: string;

  /**
   * @generated from field: types.v1.IdentityProvider identity_provider = 6;
   */
  identityProvider: IdentityProvider;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 100;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 101;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message types.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_types_v1_user, 0);

