// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=none"
// @generated from file types/v1/user.proto (package types.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file types/v1/user.proto.
 */
export const file_types_v1_user: GenFile = /*@__PURE__*/
  fileDesc("ChN0eXBlcy92MS91c2VyLnByb3RvEgh0eXBlcy52MSLkAQoEVXNlchIKCgJpZBgBIAEoBBIQCgh1c2VybmFtZRgCIAEoCRINCgVlbWFpbBgDIAEoCRIZChFwcm9maWxlX2ltYWdlX3VybBgEIAEoCRIQCghhYm91dF9tZRgFIAEoCRIiCgVncmFkZRgKIAEoDjITLnR5cGVzLnYxLlVzZXJHcmFkZRIuCgpjcmVhdGVkX2F0GGQgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIuCgp1cGRhdGVkX2F0GGUgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcCpTCglVc2VyR3JhZGUSGgoWVVNFUl9HUkFERV9VTlNQRUNJRklFRBAAEhMKD1VTRVJfR1JBREVfTk9ORRABEhUKEVVTRVJfR1JBREVfTUVNQkVSEAJCEloQdHlwZXMvdjE7dHlwZXN2MWIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message types.v1.User
 */
export type User = Message<"types.v1.User"> & {
  /**
   * @generated from field: uint64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string username = 2;
   */
  username: string;

  /**
   * @generated from field: string email = 3;
   */
  email: string;

  /**
   * @generated from field: string profile_image_url = 4;
   */
  profileImageUrl: string;

  /**
   * @generated from field: string about_me = 5;
   */
  aboutMe: string;

  /**
   * @generated from field: types.v1.UserGrade grade = 10;
   */
  grade: UserGrade;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 100;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 101;
   */
  updatedAt?: Timestamp;
};

/**
 * Describes the message types.v1.User.
 * Use `create(UserSchema)` to create a new message.
 */
export const UserSchema: GenMessage<User> = /*@__PURE__*/
  messageDesc(file_types_v1_user, 0);

/**
 * @generated from enum types.v1.UserGrade
 */
export enum UserGrade {
  /**
   * @generated from enum value: USER_GRADE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: USER_GRADE_NONE = 1;
   */
  NONE = 1,

  /**
   * @generated from enum value: USER_GRADE_MEMBER = 2;
   */
  MEMBER = 2,
}

/**
 * Describes the enum types.v1.UserGrade.
 */
export const UserGradeSchema: GenEnum<UserGrade> = /*@__PURE__*/
  enumDesc(file_types_v1_user, 0);

