// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service/auth/v1/service.proto

package authv1

import (
	v1 "github.com/gaesemo/tech-blog-api/go/types/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAuthURLRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// requried
	IdentityProvider v1.IdentityProvider `protobuf:"varint,1,opt,name=identity_provider,json=identityProvider,proto3,enum=types.v1.IdentityProvider" json:"identity_provider,omitempty"`
	RedirectUrl      *string             `protobuf:"bytes,2,opt,name=redirect_url,json=redirectUrl,proto3,oneof" json:"redirect_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAuthURLRequest) Reset() {
	*x = GetAuthURLRequest{}
	mi := &file_service_auth_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthURLRequest) ProtoMessage() {}

func (x *GetAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthURLRequest.ProtoReflect.Descriptor instead.
func (*GetAuthURLRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthURLRequest) GetIdentityProvider() v1.IdentityProvider {
	if x != nil {
		return x.IdentityProvider
	}
	return v1.IdentityProvider(0)
}

func (x *GetAuthURLRequest) GetRedirectUrl() string {
	if x != nil && x.RedirectUrl != nil {
		return *x.RedirectUrl
	}
	return ""
}

type GetAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthURLResponse) Reset() {
	*x = GetAuthURLResponse{}
	mi := &file_service_auth_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthURLResponse) ProtoMessage() {}

func (x *GetAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthURLResponse.ProtoReflect.Descriptor instead.
func (*GetAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthURLResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_service_auth_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{2}
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_service_auth_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_service_auth_v1_service_proto protoreflect.FileDescriptor

const file_service_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dservice/auth/v1/service.proto\x12\x0fservice.auth.v1\x1a types/v1/identity_provider.proto\"\x95\x01\n" +
	"\x11GetAuthURLRequest\x12G\n" +
	"\x11identity_provider\x18\x01 \x01(\x0e2\x1a.types.v1.IdentityProviderR\x10identityProvider\x12&\n" +
	"\fredirect_url\x18\x02 \x01(\tH\x00R\vredirectUrl\x88\x01\x01B\x0f\n" +
	"\r_redirect_url\"/\n" +
	"\x12GetAuthURLResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\"\x0f\n" +
	"\rLogoutRequest\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb3\x01\n" +
	"\vAuthService\x12W\n" +
	"\n" +
	"GetAuthURL\x12\".service.auth.v1.GetAuthURLRequest\x1a#.service.auth.v1.GetAuthURLResponse\"\x00\x12K\n" +
	"\x06Logout\x12\x1e.service.auth.v1.LogoutRequest\x1a\x1f.service.auth.v1.LogoutResponse\"\x00B<Z:github.com/gaesemo/tech-blog-api/go/service/auth/v1;authv1b\x06proto3"

var (
	file_service_auth_v1_service_proto_rawDescOnce sync.Once
	file_service_auth_v1_service_proto_rawDescData []byte
)

func file_service_auth_v1_service_proto_rawDescGZIP() []byte {
	file_service_auth_v1_service_proto_rawDescOnce.Do(func() {
		file_service_auth_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_auth_v1_service_proto_rawDesc), len(file_service_auth_v1_service_proto_rawDesc)))
	})
	return file_service_auth_v1_service_proto_rawDescData
}

var file_service_auth_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_service_auth_v1_service_proto_goTypes = []any{
	(*GetAuthURLRequest)(nil),  // 0: service.auth.v1.GetAuthURLRequest
	(*GetAuthURLResponse)(nil), // 1: service.auth.v1.GetAuthURLResponse
	(*LogoutRequest)(nil),      // 2: service.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),     // 3: service.auth.v1.LogoutResponse
	(v1.IdentityProvider)(0),   // 4: types.v1.IdentityProvider
}
var file_service_auth_v1_service_proto_depIdxs = []int32{
	4, // 0: service.auth.v1.GetAuthURLRequest.identity_provider:type_name -> types.v1.IdentityProvider
	0, // 1: service.auth.v1.AuthService.GetAuthURL:input_type -> service.auth.v1.GetAuthURLRequest
	2, // 2: service.auth.v1.AuthService.Logout:input_type -> service.auth.v1.LogoutRequest
	1, // 3: service.auth.v1.AuthService.GetAuthURL:output_type -> service.auth.v1.GetAuthURLResponse
	3, // 4: service.auth.v1.AuthService.Logout:output_type -> service.auth.v1.LogoutResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_auth_v1_service_proto_init() }
func file_service_auth_v1_service_proto_init() {
	if File_service_auth_v1_service_proto != nil {
		return
	}
	file_service_auth_v1_service_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_auth_v1_service_proto_rawDesc), len(file_service_auth_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_service_auth_v1_service_proto_depIdxs,
		MessageInfos:      file_service_auth_v1_service_proto_msgTypes,
	}.Build()
	File_service_auth_v1_service_proto = out.File
	file_service_auth_v1_service_proto_goTypes = nil
	file_service_auth_v1_service_proto_depIdxs = nil
}
