// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: service/auth/v1/service.proto

package authv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthProvider int32

const (
	AuthProvider_AUTH_PROVIDER_UNSPECIFIED AuthProvider = 0
	AuthProvider_AUTH_PROVIDER_GITHUB      AuthProvider = 1
)

// Enum value maps for AuthProvider.
var (
	AuthProvider_name = map[int32]string{
		0: "AUTH_PROVIDER_UNSPECIFIED",
		1: "AUTH_PROVIDER_GITHUB",
	}
	AuthProvider_value = map[string]int32{
		"AUTH_PROVIDER_UNSPECIFIED": 0,
		"AUTH_PROVIDER_GITHUB":      1,
	}
)

func (x AuthProvider) Enum() *AuthProvider {
	p := new(AuthProvider)
	*p = x
	return p
}

func (x AuthProvider) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthProvider) Descriptor() protoreflect.EnumDescriptor {
	return file_service_auth_v1_service_proto_enumTypes[0].Descriptor()
}

func (AuthProvider) Type() protoreflect.EnumType {
	return &file_service_auth_v1_service_proto_enumTypes[0]
}

func (x AuthProvider) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthProvider.Descriptor instead.
func (AuthProvider) EnumDescriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{0}
}

type GetAuthURLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthProvider  AuthProvider           `protobuf:"varint,1,opt,name=auth_provider,json=authProvider,proto3,enum=service.auth.v1.AuthProvider" json:"auth_provider,omitempty"`
	CallbackUrl   string                 `protobuf:"bytes,2,opt,name=callback_url,json=callbackUrl,proto3" json:"callback_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthURLRequest) Reset() {
	*x = GetAuthURLRequest{}
	mi := &file_service_auth_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthURLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthURLRequest) ProtoMessage() {}

func (x *GetAuthURLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthURLRequest.ProtoReflect.Descriptor instead.
func (*GetAuthURLRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetAuthURLRequest) GetAuthProvider() AuthProvider {
	if x != nil {
		return x.AuthProvider
	}
	return AuthProvider_AUTH_PROVIDER_UNSPECIFIED
}

func (x *GetAuthURLRequest) GetCallbackUrl() string {
	if x != nil {
		return x.CallbackUrl
	}
	return ""
}

type GetAuthURLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthUrl       string                 `protobuf:"bytes,1,opt,name=auth_url,json=authUrl,proto3" json:"auth_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuthURLResponse) Reset() {
	*x = GetAuthURLResponse{}
	mi := &file_service_auth_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuthURLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuthURLResponse) ProtoMessage() {}

func (x *GetAuthURLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuthURLResponse.ProtoReflect.Descriptor instead.
func (*GetAuthURLResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuthURLResponse) GetAuthUrl() string {
	if x != nil {
		return x.AuthUrl
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthProvider  AuthProvider           `protobuf:"varint,1,opt,name=auth_provider,json=authProvider,proto3,enum=service.auth.v1.AuthProvider" json:"auth_provider,omitempty"`
	AuthCode      string                 `protobuf:"bytes,2,opt,name=auth_code,json=authCode,proto3" json:"auth_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_service_auth_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetAuthProvider() AuthProvider {
	if x != nil {
		return x.AuthProvider
	}
	return AuthProvider_AUTH_PROVIDER_UNSPECIFIED
}

func (x *LoginRequest) GetAuthCode() string {
	if x != nil {
		return x.AuthCode
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // jwt
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`       // uuid
	IsNewUser     bool                   `protobuf:"varint,3,opt,name=is_new_user,json=isNewUser,proto3" json:"is_new_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_service_auth_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *LoginResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *LoginResponse) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_service_auth_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *LogoutRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_service_auth_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_auth_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_service_auth_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_service_auth_v1_service_proto protoreflect.FileDescriptor

const file_service_auth_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x1dservice/auth/v1/service.proto\x12\x0fservice.auth.v1\"z\n" +
	"\x11GetAuthURLRequest\x12B\n" +
	"\rauth_provider\x18\x01 \x01(\x0e2\x1d.service.auth.v1.AuthProviderR\fauthProvider\x12!\n" +
	"\fcallback_url\x18\x02 \x01(\tR\vcallbackUrl\"/\n" +
	"\x12GetAuthURLResponse\x12\x19\n" +
	"\bauth_url\x18\x01 \x01(\tR\aauthUrl\"o\n" +
	"\fLoginRequest\x12B\n" +
	"\rauth_provider\x18\x01 \x01(\x0e2\x1d.service.auth.v1.AuthProviderR\fauthProvider\x12\x1b\n" +
	"\tauth_code\x18\x02 \x01(\tR\bauthCode\"q\n" +
	"\rLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1e\n" +
	"\vis_new_user\x18\x03 \x01(\bR\tisNewUser\".\n" +
	"\rLogoutRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess*G\n" +
	"\fAuthProvider\x12\x1d\n" +
	"\x19AUTH_PROVIDER_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14AUTH_PROVIDER_GITHUB\x10\x012\xfd\x01\n" +
	"\vAuthService\x12W\n" +
	"\n" +
	"GetAuthURL\x12\".service.auth.v1.GetAuthURLRequest\x1a#.service.auth.v1.GetAuthURLResponse\"\x00\x12H\n" +
	"\x05Login\x12\x1d.service.auth.v1.LoginRequest\x1a\x1e.service.auth.v1.LoginResponse\"\x00\x12K\n" +
	"\x06Logout\x12\x1e.service.auth.v1.LogoutRequest\x1a\x1f.service.auth.v1.LogoutResponse\"\x00B<Z:github.com/gaesemo/tech-blog-api/go/service/auth/v1;authv1b\x06proto3"

var (
	file_service_auth_v1_service_proto_rawDescOnce sync.Once
	file_service_auth_v1_service_proto_rawDescData []byte
)

func file_service_auth_v1_service_proto_rawDescGZIP() []byte {
	file_service_auth_v1_service_proto_rawDescOnce.Do(func() {
		file_service_auth_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_auth_v1_service_proto_rawDesc), len(file_service_auth_v1_service_proto_rawDesc)))
	})
	return file_service_auth_v1_service_proto_rawDescData
}

var file_service_auth_v1_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_auth_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_service_auth_v1_service_proto_goTypes = []any{
	(AuthProvider)(0),          // 0: service.auth.v1.AuthProvider
	(*GetAuthURLRequest)(nil),  // 1: service.auth.v1.GetAuthURLRequest
	(*GetAuthURLResponse)(nil), // 2: service.auth.v1.GetAuthURLResponse
	(*LoginRequest)(nil),       // 3: service.auth.v1.LoginRequest
	(*LoginResponse)(nil),      // 4: service.auth.v1.LoginResponse
	(*LogoutRequest)(nil),      // 5: service.auth.v1.LogoutRequest
	(*LogoutResponse)(nil),     // 6: service.auth.v1.LogoutResponse
}
var file_service_auth_v1_service_proto_depIdxs = []int32{
	0, // 0: service.auth.v1.GetAuthURLRequest.auth_provider:type_name -> service.auth.v1.AuthProvider
	0, // 1: service.auth.v1.LoginRequest.auth_provider:type_name -> service.auth.v1.AuthProvider
	1, // 2: service.auth.v1.AuthService.GetAuthURL:input_type -> service.auth.v1.GetAuthURLRequest
	3, // 3: service.auth.v1.AuthService.Login:input_type -> service.auth.v1.LoginRequest
	5, // 4: service.auth.v1.AuthService.Logout:input_type -> service.auth.v1.LogoutRequest
	2, // 5: service.auth.v1.AuthService.GetAuthURL:output_type -> service.auth.v1.GetAuthURLResponse
	4, // 6: service.auth.v1.AuthService.Login:output_type -> service.auth.v1.LoginResponse
	6, // 7: service.auth.v1.AuthService.Logout:output_type -> service.auth.v1.LogoutResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_service_auth_v1_service_proto_init() }
func file_service_auth_v1_service_proto_init() {
	if File_service_auth_v1_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_auth_v1_service_proto_rawDesc), len(file_service_auth_v1_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_auth_v1_service_proto_goTypes,
		DependencyIndexes: file_service_auth_v1_service_proto_depIdxs,
		EnumInfos:         file_service_auth_v1_service_proto_enumTypes,
		MessageInfos:      file_service_auth_v1_service_proto_msgTypes,
	}.Build()
	File_service_auth_v1_service_proto = out.File
	file_service_auth_v1_service_proto_goTypes = nil
	file_service_auth_v1_service_proto_depIdxs = nil
}
